
version: '3.3'

services:
  vite-ui:
    build: ./client
    working_dir: '/client'
    command: 'npm run dev'
    volumes: 
      - ./client:/client
    depends_on: 
      - go-api
    ports:
      - 3000:3000
  go-api:
    build: ./server
    working_dir: '/go/src/github.com/NathanBland/go-vite-docker-starter'
    command: 'air'
    volumes:
      - ./server:/go/src/github.com/NathanBland/go-vite-docker-starter
    depends_on:
      - mongo-db
    environment:
      HOST: 0.0.0.0
      ENV: development
    ports:
      - 3001:3001
  mongo-db:
    image: 'mongo:4'