// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Note struct {
	ID          uuid.UUID          `json:"id"`
	OwnerUserID uuid.UUID          `json:"owner_user_id"`
	Title       *string            `json:"title"`
	Content     string             `json:"content"`
	Tags        []string           `json:"tags"`
	Archived    bool               `json:"archived"`
	Shared      bool               `json:"shared"`
	ShareSlug   *string            `json:"share_slug"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SavedQuery struct {
	ID          uuid.UUID          `json:"id"`
	OwnerUserID uuid.UUID          `json:"owner_user_id"`
	Name        string             `json:"name"`
	QueryString string             `json:"query_string"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID            uuid.UUID          `json:"id"`
	OidcIssuer    string             `json:"oidc_issuer"`
	OidcSubject   string             `json:"oidc_subject"`
	Email         *string            `json:"email"`
	EmailVerified bool               `json:"email_verified"`
	DisplayName   *string            `json:"display_name"`
	PictureUrl    *string            `json:"picture_url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
