// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countNotesForOwner = `-- name: CountNotesForOwner :one
SELECT count(*)
FROM notes
WHERE owner_user_id = $1
  AND (
    $2::text = 'all'
    OR ($2::text = 'active' AND archived = false)
    OR ($2::text = 'archived' AND archived = true)
  )
  AND ($3::boolean IS NULL OR shared = $3::boolean)
  AND (
    $4::boolean IS NULL
    OR (
      $4::boolean = true
      AND NULLIF(BTRIM(COALESCE(title, '')), '') IS NOT NULL
    )
    OR (
      $4::boolean = false
      AND NULLIF(BTRIM(COALESCE(title, '')), '') IS NULL
    )
  )
  AND (
    NOT $5::boolean
    OR (
      $6::text = 'all'
      AND tags @> $7::text[]
    )
    OR (
      $6::text = 'any'
      AND tags && $7::text[]
    )
  )
  AND ($8::int IS NULL OR cardinality(tags) >= $8::int)
  AND ($9::int IS NULL OR cardinality(tags) <= $9::int)
  AND (
    $10::text IS NULL
    OR (
      $11::text = 'plain'
      AND (
        COALESCE(title, '') ILIKE '%' || $10::text || '%'
        OR content ILIKE '%' || $10::text || '%'
      )
    )
    OR (
      $11::text = 'fts'
      AND websearch_to_tsquery('english', $10::text) @@ to_tsvector('english', COALESCE(title, '') || ' ' || content)
    )
  )
  AND ($12::timestamptz IS NULL OR created_at >= $12::timestamptz)
  AND ($13::timestamptz IS NULL OR created_at <= $13::timestamptz)
  AND ($14::timestamptz IS NULL OR updated_at >= $14::timestamptz)
  AND ($15::timestamptz IS NULL OR updated_at <= $15::timestamptz)
`

type CountNotesForOwnerParams struct {
	OwnerUserID         uuid.UUID          `json:"owner_user_id"`
	StatusFilter        string             `json:"status_filter"`
	SharedFilter        *bool              `json:"shared_filter"`
	HasTitleFilter      *bool              `json:"has_title_filter"`
	TagFilterEnabled    bool               `json:"tag_filter_enabled"`
	TagMatchMode        string             `json:"tag_match_mode"`
	TagFilters          []string           `json:"tag_filters"`
	TagCountMinFilter   *int32             `json:"tag_count_min_filter"`
	TagCountMaxFilter   *int32             `json:"tag_count_max_filter"`
	SearchFilter        *string            `json:"search_filter"`
	SearchMode          string             `json:"search_mode"`
	CreatedAfterFilter  pgtype.Timestamptz `json:"created_after_filter"`
	CreatedBeforeFilter pgtype.Timestamptz `json:"created_before_filter"`
	UpdatedAfterFilter  pgtype.Timestamptz `json:"updated_after_filter"`
	UpdatedBeforeFilter pgtype.Timestamptz `json:"updated_before_filter"`
}

// Count uses the same filters as ListNotesForOwner so pagination metadata
// stays consistent with the actual result set.
func (q *Queries) CountNotesForOwner(ctx context.Context, arg CountNotesForOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNotesForOwner,
		arg.OwnerUserID,
		arg.StatusFilter,
		arg.SharedFilter,
		arg.HasTitleFilter,
		arg.TagFilterEnabled,
		arg.TagMatchMode,
		arg.TagFilters,
		arg.TagCountMinFilter,
		arg.TagCountMaxFilter,
		arg.SearchFilter,
		arg.SearchMode,
		arg.CreatedAfterFilter,
		arg.CreatedBeforeFilter,
		arg.UpdatedAfterFilter,
		arg.UpdatedBeforeFilter,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNote = `-- name: CreateNote :one
INSERT INTO notes (
    owner_user_id,
    title,
    content,
    tags,
    archived,
    shared,
    share_slug
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, owner_user_id, title, content, tags, archived, shared, share_slug, created_at, updated_at
`

type CreateNoteParams struct {
	OwnerUserID uuid.UUID `json:"owner_user_id"`
	Title       *string   `json:"title"`
	Content     string    `json:"content"`
	Tags        []string  `json:"tags"`
	Archived    bool      `json:"archived"`
	Shared      bool      `json:"shared"`
	ShareSlug   *string   `json:"share_slug"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.OwnerUserID,
		arg.Title,
		arg.Content,
		arg.Tags,
		arg.Archived,
		arg.Shared,
		arg.ShareSlug,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.Archived,
		&i.Shared,
		&i.ShareSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNoteForOwner = `-- name: DeleteNoteForOwner :execrows
DELETE FROM notes
WHERE id = $1
  AND owner_user_id = $2
`

type DeleteNoteForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) DeleteNoteForOwner(ctx context.Context, arg DeleteNoteForOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNoteForOwner, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findRelatedNotesForOwner = `-- name: FindRelatedNotesForOwner :many
WITH source AS (
    SELECT tags
    FROM notes
    WHERE notes.id = $2
      AND notes.owner_user_id = $3
),
related AS (
    SELECT
        n.id, n.owner_user_id, n.title, n.content, n.tags, n.archived, n.shared, n.share_slug, n.created_at, n.updated_at,
        COALESCE(shared.shared_tags, ARRAY[]::text[])::text[] AS shared_tags,
        cardinality(COALESCE(shared.shared_tags, ARRAY[]::text[])::text[])::int AS shared_tag_count
    FROM notes AS n
    CROSS JOIN source
    CROSS JOIN LATERAL (
        SELECT array_agg(tag ORDER BY lower(tag), tag) AS shared_tags
        FROM (
            SELECT DISTINCT tag
            FROM unnest(n.tags) AS note_tag(tag)
            WHERE btrim(tag) <> ''
            INTERSECT
            SELECT DISTINCT tag
            FROM unnest(source.tags) AS source_tag(tag)
            WHERE btrim(tag) <> ''
        ) AS overlap
    ) AS shared
    WHERE n.owner_user_id = $3
      AND n.id <> $2
)
SELECT id, owner_user_id, title, content, tags, archived, shared, share_slug, created_at, updated_at, shared_tags, shared_tag_count
FROM related
WHERE shared_tag_count > 0
ORDER BY shared_tag_count DESC, lower(COALESCE(title, '')) ASC, related.id ASC
LIMIT $1
`

type FindRelatedNotesForOwnerParams struct {
	LimitCount  int32     `json:"limit_count"`
	NoteID      uuid.UUID `json:"note_id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

type FindRelatedNotesForOwnerRow struct {
	ID             uuid.UUID          `json:"id"`
	OwnerUserID    uuid.UUID          `json:"owner_user_id"`
	Title          *string            `json:"title"`
	Content        string             `json:"content"`
	Tags           []string           `json:"tags"`
	Archived       bool               `json:"archived"`
	Shared         bool               `json:"shared"`
	ShareSlug      *string            `json:"share_slug"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	SharedTags     []string           `json:"shared_tags"`
	SharedTagCount int32              `json:"shared_tag_count"`
}

// Related-note discovery intentionally stays in SQL so overlap ranking,
// owner scoping, and deterministic ordering are shared by every caller.
func (q *Queries) FindRelatedNotesForOwner(ctx context.Context, arg FindRelatedNotesForOwnerParams) ([]FindRelatedNotesForOwnerRow, error) {
	rows, err := q.db.Query(ctx, findRelatedNotesForOwner, arg.LimitCount, arg.NoteID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindRelatedNotesForOwnerRow{}
	for rows.Next() {
		var i FindRelatedNotesForOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Title,
			&i.Content,
			&i.Tags,
			&i.Archived,
			&i.Shared,
			&i.ShareSlug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SharedTags,
			&i.SharedTagCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNoteByIDForOwner = `-- name: GetNoteByIDForOwner :one
SELECT id, owner_user_id, title, content, tags, archived, shared, share_slug, created_at, updated_at
FROM notes
WHERE id = $1
  AND owner_user_id = $2
`

type GetNoteByIDForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) GetNoteByIDForOwner(ctx context.Context, arg GetNoteByIDForOwnerParams) (Note, error) {
	row := q.db.QueryRow(ctx, getNoteByIDForOwner, arg.ID, arg.OwnerUserID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.Archived,
		&i.Shared,
		&i.ShareSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNoteByShareSlug = `-- name: GetNoteByShareSlug :one
SELECT id, owner_user_id, title, content, tags, archived, shared, share_slug, created_at, updated_at
FROM notes
WHERE share_slug = $1
  AND shared = true
`

func (q *Queries) GetNoteByShareSlug(ctx context.Context, shareSlug *string) (Note, error) {
	row := q.db.QueryRow(ctx, getNoteByShareSlug, shareSlug)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.Archived,
		&i.Shared,
		&i.ShareSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotesForOwner = `-- name: ListNotesForOwner :many
SELECT id, owner_user_id, title, content, tags, archived, shared, share_slug, created_at, updated_at
FROM notes
WHERE owner_user_id = $1
  AND (
    $2::text = 'all'
    OR ($2::text = 'active' AND archived = false)
    OR ($2::text = 'archived' AND archived = true)
  )
  AND ($3::boolean IS NULL OR shared = $3::boolean)
  AND (
    $4::boolean IS NULL
    OR (
      $4::boolean = true
      AND NULLIF(BTRIM(COALESCE(title, '')), '') IS NOT NULL
    )
    OR (
      $4::boolean = false
      AND NULLIF(BTRIM(COALESCE(title, '')), '') IS NULL
    )
  )
  AND (
    NOT $5::boolean
    OR (
      $6::text = 'all'
      AND tags @> $7::text[]
    )
    OR (
      $6::text = 'any'
      AND tags && $7::text[]
    )
  )
  AND ($8::int IS NULL OR cardinality(tags) >= $8::int)
  AND ($9::int IS NULL OR cardinality(tags) <= $9::int)
  AND (
    $10::text IS NULL
    OR (
      $11::text = 'plain'
      AND (
        COALESCE(title, '') ILIKE '%' || $10::text || '%'
        OR content ILIKE '%' || $10::text || '%'
      )
    )
    OR (
      $11::text = 'fts'
      AND websearch_to_tsquery('english', $10::text) @@ to_tsvector('english', COALESCE(title, '') || ' ' || content)
    )
  )
  AND ($12::timestamptz IS NULL OR created_at >= $12::timestamptz)
  AND ($13::timestamptz IS NULL OR created_at <= $13::timestamptz)
  AND ($14::timestamptz IS NULL OR updated_at >= $14::timestamptz)
  AND ($15::timestamptz IS NULL OR updated_at <= $15::timestamptz)
ORDER BY
  CASE WHEN $16::text = 'title' AND $17::text = 'asc' THEN lower(COALESCE(title, '')) END ASC,
  CASE WHEN $16::text = 'title' AND $17::text = 'desc' THEN lower(COALESCE(title, '')) END DESC,
  -- PostgreSQL arrays are 1-based, so tags[1] means "the first stored tag".
  -- Empty arrays return NULL here, which lets us keep a deterministic
  -- SQL-side primary-tag sort without pushing custom ordering logic into Go.
  CASE WHEN $16::text = 'primary_tag' AND $17::text = 'asc' THEN lower(COALESCE(tags[1], '')) END ASC,
  CASE WHEN $16::text = 'primary_tag' AND $17::text = 'desc' THEN lower(COALESCE(tags[1], '')) END DESC,
  CASE WHEN $16::text = 'created_at' AND $17::text = 'asc' THEN created_at END ASC,
  CASE WHEN $16::text = 'created_at' AND $17::text = 'desc' THEN created_at END DESC,
  CASE WHEN $16::text = 'updated_at' AND $17::text = 'asc' THEN updated_at END ASC,
  CASE WHEN $16::text = 'updated_at' AND $17::text = 'desc' THEN updated_at END DESC,
  CASE WHEN $16::text = 'tag_count' AND $17::text = 'asc' THEN cardinality(tags) END ASC,
  CASE WHEN $16::text = 'tag_count' AND $17::text = 'desc' THEN cardinality(tags) END DESC,
  CASE WHEN $16::text = 'relevance' AND $17::text = 'asc' THEN ts_rank_cd(to_tsvector('english', COALESCE(title, '') || ' ' || content), websearch_to_tsquery('english', COALESCE($10::text, '')), 32) END ASC,
  CASE WHEN $16::text = 'relevance' AND $17::text = 'desc' THEN ts_rank_cd(to_tsvector('english', COALESCE(title, '') || ' ' || content), websearch_to_tsquery('english', COALESCE($10::text, '')), 32) END DESC,
  id ASC
LIMIT $19
OFFSET $18
`

type ListNotesForOwnerParams struct {
	OwnerUserID         uuid.UUID          `json:"owner_user_id"`
	StatusFilter        string             `json:"status_filter"`
	SharedFilter        *bool              `json:"shared_filter"`
	HasTitleFilter      *bool              `json:"has_title_filter"`
	TagFilterEnabled    bool               `json:"tag_filter_enabled"`
	TagMatchMode        string             `json:"tag_match_mode"`
	TagFilters          []string           `json:"tag_filters"`
	TagCountMinFilter   *int32             `json:"tag_count_min_filter"`
	TagCountMaxFilter   *int32             `json:"tag_count_max_filter"`
	SearchFilter        *string            `json:"search_filter"`
	SearchMode          string             `json:"search_mode"`
	CreatedAfterFilter  pgtype.Timestamptz `json:"created_after_filter"`
	CreatedBeforeFilter pgtype.Timestamptz `json:"created_before_filter"`
	UpdatedAfterFilter  pgtype.Timestamptz `json:"updated_after_filter"`
	UpdatedBeforeFilter pgtype.Timestamptz `json:"updated_before_filter"`
	SortField           string             `json:"sort_field"`
	SortDirection       string             `json:"sort_direction"`
	OffsetCount         int32              `json:"offset_count"`
	LimitCount          int32              `json:"limit_count"`
}

// Filtering, sorting, pagination, and total counts intentionally live in SQL.
// That keeps the API behavior authoritative and lets PostgreSQL do the work it
// is good at. User-controlled values stay bound through sqlc args/nargs, and
// sort behavior is limited to CASE-based allowlists instead of interpolated SQL
// strings.
func (q *Queries) ListNotesForOwner(ctx context.Context, arg ListNotesForOwnerParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotesForOwner,
		arg.OwnerUserID,
		arg.StatusFilter,
		arg.SharedFilter,
		arg.HasTitleFilter,
		arg.TagFilterEnabled,
		arg.TagMatchMode,
		arg.TagFilters,
		arg.TagCountMinFilter,
		arg.TagCountMaxFilter,
		arg.SearchFilter,
		arg.SearchMode,
		arg.CreatedAfterFilter,
		arg.CreatedBeforeFilter,
		arg.UpdatedAfterFilter,
		arg.UpdatedBeforeFilter,
		arg.SortField,
		arg.SortDirection,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Title,
			&i.Content,
			&i.Tags,
			&i.Archived,
			&i.Shared,
			&i.ShareSlug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForOwner = `-- name: ListTagsForOwner :many
SELECT
    expanded.tag::text AS tag,
    count(*)::bigint AS count
FROM notes
CROSS JOIN LATERAL unnest(tags) AS expanded(tag)
WHERE owner_user_id = $1
  AND btrim(expanded.tag) <> ''
GROUP BY expanded.tag
ORDER BY count(*) DESC, lower(expanded.tag) ASC, expanded.tag ASC
`

type ListTagsForOwnerRow struct {
	Tag   string `json:"tag"`
	Count int64  `json:"count"`
}

// Tag discovery intentionally happens in SQL so every caller gets the same
// owner scoping, counting, and deterministic ordering behavior.
func (q *Queries) ListTagsForOwner(ctx context.Context, ownerUserID uuid.UUID) ([]ListTagsForOwnerRow, error) {
	rows, err := q.db.Query(ctx, listTagsForOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsForOwnerRow{}
	for rows.Next() {
		var i ListTagsForOwnerRow
		if err := rows.Scan(&i.Tag, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotePatch = `-- name: UpdateNotePatch :one
UPDATE notes
SET
    title = CASE
        WHEN $1::boolean THEN $2::text
        ELSE title
    END,
    content = CASE
        WHEN $3::boolean THEN $4::text
        ELSE content
    END,
    tags = CASE
        WHEN $5::boolean THEN $6::text[]
        ELSE tags
    END,
    archived = CASE
        WHEN $7::boolean THEN $8::boolean
        ELSE archived
    END,
    shared = CASE
        WHEN $9::boolean THEN $10::boolean
        ELSE shared
    END,
    share_slug = CASE
        WHEN $11::boolean THEN $12::text
        ELSE share_slug
    END,
    updated_at = now()
WHERE id = $13
  AND owner_user_id = $14
RETURNING id, owner_user_id, title, content, tags, archived, shared, share_slug, created_at, updated_at
`

type UpdateNotePatchParams struct {
	TitleIsSet     bool      `json:"title_is_set"`
	Title          *string   `json:"title"`
	ContentIsSet   bool      `json:"content_is_set"`
	Content        *string   `json:"content"`
	TagsIsSet      bool      `json:"tags_is_set"`
	Tags           []string  `json:"tags"`
	ArchivedIsSet  bool      `json:"archived_is_set"`
	Archived       bool      `json:"archived"`
	SharedIsSet    bool      `json:"shared_is_set"`
	Shared         bool      `json:"shared"`
	ShareSlugIsSet bool      `json:"share_slug_is_set"`
	ShareSlug      *string   `json:"share_slug"`
	ID             uuid.UUID `json:"id"`
	OwnerUserID    uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) UpdateNotePatch(ctx context.Context, arg UpdateNotePatchParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNotePatch,
		arg.TitleIsSet,
		arg.Title,
		arg.ContentIsSet,
		arg.Content,
		arg.TagsIsSet,
		arg.Tags,
		arg.ArchivedIsSet,
		arg.Archived,
		arg.SharedIsSet,
		arg.Shared,
		arg.ShareSlugIsSet,
		arg.ShareSlug,
		arg.ID,
		arg.OwnerUserID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.Archived,
		&i.Shared,
		&i.ShareSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
