// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: saved_queries.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
)

const createSavedQuery = `-- name: CreateSavedQuery :one
INSERT INTO saved_queries (
    owner_user_id,
    name,
    query_string
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, owner_user_id, name, query_string, created_at, updated_at
`

type CreateSavedQueryParams struct {
	OwnerUserID uuid.UUID `json:"owner_user_id"`
	Name        string    `json:"name"`
	QueryString string    `json:"query_string"`
}

func (q *Queries) CreateSavedQuery(ctx context.Context, arg CreateSavedQueryParams) (SavedQuery, error) {
	row := q.db.QueryRow(ctx, createSavedQuery, arg.OwnerUserID, arg.Name, arg.QueryString)
	var i SavedQuery
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.QueryString,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSavedQueryForOwner = `-- name: DeleteSavedQueryForOwner :execrows
DELETE FROM saved_queries
WHERE id = $1
  AND owner_user_id = $2
`

type DeleteSavedQueryForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) DeleteSavedQueryForOwner(ctx context.Context, arg DeleteSavedQueryForOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSavedQueryForOwner, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSavedQueryForOwner = `-- name: GetSavedQueryForOwner :one
SELECT id, owner_user_id, name, query_string, created_at, updated_at
FROM saved_queries
WHERE id = $1
  AND owner_user_id = $2
`

type GetSavedQueryForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) GetSavedQueryForOwner(ctx context.Context, arg GetSavedQueryForOwnerParams) (SavedQuery, error) {
	row := q.db.QueryRow(ctx, getSavedQueryForOwner, arg.ID, arg.OwnerUserID)
	var i SavedQuery
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.QueryString,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSavedQueriesForOwner = `-- name: ListSavedQueriesForOwner :many
SELECT id, owner_user_id, name, query_string, created_at, updated_at
FROM saved_queries
WHERE owner_user_id = $1
ORDER BY lower(name) ASC, name ASC, id ASC
`

func (q *Queries) ListSavedQueriesForOwner(ctx context.Context, ownerUserID uuid.UUID) ([]SavedQuery, error) {
	rows, err := q.db.Query(ctx, listSavedQueriesForOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedQuery{}
	for rows.Next() {
		var i SavedQuery
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.QueryString,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
