// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, oidc_issuer, oidc_subject, email, email_verified, display_name, picture_url, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.PictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserFromOIDC = `-- name: UpsertUserFromOIDC :one
INSERT INTO users (
    oidc_issuer,
    oidc_subject,
    email,
    email_verified,
    display_name,
    picture_url
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (oidc_issuer, oidc_subject)
DO UPDATE SET
    email = EXCLUDED.email,
    email_verified = EXCLUDED.email_verified,
    display_name = EXCLUDED.display_name,
    picture_url = EXCLUDED.picture_url,
    updated_at = now()
RETURNING id, oidc_issuer, oidc_subject, email, email_verified, display_name, picture_url, created_at, updated_at
`

type UpsertUserFromOIDCParams struct {
	OidcIssuer    string  `json:"oidc_issuer"`
	OidcSubject   string  `json:"oidc_subject"`
	Email         *string `json:"email"`
	EmailVerified bool    `json:"email_verified"`
	DisplayName   *string `json:"display_name"`
	PictureUrl    *string `json:"picture_url"`
}

func (q *Queries) UpsertUserFromOIDC(ctx context.Context, arg UpsertUserFromOIDCParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserFromOIDC,
		arg.OidcIssuer,
		arg.OidcSubject,
		arg.Email,
		arg.EmailVerified,
		arg.DisplayName,
		arg.PictureUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.PictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
