FROM golang:alpine 

WORKDIR /go/src/github.com/NathanBland/go-vite-docker-starter
# COPY . .

RUN apk add git

RUN go get -u github.com/cosmtrek/air

# RUN go mod init
# RUN go get go.mongodb.org/mongo-driver

# RUN go get -d -v ./...
# RUN go install -v ./...

# CMD ["air"]